" Name:         Gruvbox 8
" Description:  Retro groove color scheme originally designed by morhetz
" Author:       morhetz <morhetz@gmail.com>
" Maintainer:   Lifepillar <lifepillar@lifepillar.me>
" Website:      https://github.com/lifepillar/vim-gruvbox8/
" License:      Vim License (see `:help license`)
" Last Updated: Sun Mar 20 16:00:31 2022

" Generated by Colortemplate v2.2.0

hi clear
let g:colors_name = 'gruvbox8'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 1
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

let s:italics = s:italics && get(g:, 'gruvbox_italics', 1)
hi! link CursorColumn CursorLine
hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link VisualNOS Visual
hi! link Tag Special
hi! link lCursor Cursor
hi! link iCursor Cursor
hi! link vCursor Cursor

if &background ==# 'dark'
  if (has('termguicolors') && &termguicolors) || has('gui_running')
    let g:terminal_ansi_colors = ['#282828', '#cc241d', '#98971a', '#d79921', '#458588', '#b16286', '#689d6a', '#a89984', '#928374', '#fb4934', '#b8bb26', '#fabd2f', '#83a598', '#d3869b', '#8ec07c', '#ebdbb2']
  endif
  if has('nvim')
    let g:terminal_color_0 = '#282828'
    let g:terminal_color_1 = '#cc241d'
    let g:terminal_color_2 = '#98971a'
    let g:terminal_color_3 = '#d79921'
    let g:terminal_color_4 = '#458588'
    let g:terminal_color_5 = '#b16286'
    let g:terminal_color_6 = '#689d6a'
    let g:terminal_color_7 = '#a89984'
    let g:terminal_color_8 = '#928374'
    let g:terminal_color_9 = '#fb4934'
    let g:terminal_color_10 = '#b8bb26'
    let g:terminal_color_11 = '#fabd2f'
    let g:terminal_color_12 = '#83a598'
    let g:terminal_color_13 = '#d3869b'
    let g:terminal_color_14 = '#8ec07c'
    let g:terminal_color_15 = '#ebdbb2'
  endif
  if get(g:, 'gruvbox_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
    hi CursorLineNr guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
    hi FoldColumn guifg=#928374 guibg=NONE gui=NONE cterm=NONE
    hi SignColumn guifg=#ebdbb2 guibg=NONE gui=NONE cterm=NONE
    hi VertSplit guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#ebdbb2 guibg=#282828 gui=NONE cterm=NONE
    hi CursorLineNr guifg=#fabd2f guibg=#3c3836 gui=NONE cterm=NONE
    hi FoldColumn guifg=#928374 guibg=#3c3836 gui=NONE cterm=NONE
    hi SignColumn guifg=#ebdbb2 guibg=#3c3836 gui=NONE cterm=NONE
    hi VertSplit guifg=#665c54 guibg=#282828 gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=#3c3836 gui=NONE cterm=NONE
  hi Comment guifg=#928374 guibg=NONE gui=italic cterm=italic
  hi CursorLine guifg=NONE guibg=#3c3836 gui=NONE cterm=NONE
  hi Error guifg=#fb4934 guibg=#282828 gui=bold,reverse cterm=bold,reverse
  hi ErrorMsg guifg=#282828 guibg=#fb4934 gui=bold cterm=bold
  hi Folded guifg=#928374 guibg=#3c3836 gui=italic cterm=italic
  hi LineNr guifg=#7c6f64 guibg=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=NONE guibg=#504945 gui=bold,underline cterm=bold,underline
  hi NonText guifg=#504945 guibg=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#ebdbb2 guibg=#504945 gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#504945 gui=NONE cterm=NONE
  hi PmenuSel guifg=#504945 guibg=#83a598 gui=bold cterm=bold
  hi PmenuThumb guifg=NONE guibg=#7c6f64 gui=NONE cterm=NONE
  hi SpecialKey guifg=#928374 guibg=NONE gui=NONE cterm=NONE
  hi StatusLine guifg=#504945 guibg=#ebdbb2 gui=reverse cterm=reverse
  hi StatusLineNC guifg=#3c3836 guibg=#a89984 gui=reverse cterm=reverse
  hi TabLine guifg=#7c6f64 guibg=#3c3836 gui=NONE cterm=NONE
  hi TabLineFill guifg=#7c6f64 guibg=#3c3836 gui=NONE cterm=NONE
  hi TabLineSel guifg=#b8bb26 guibg=#3c3836 gui=NONE cterm=NONE
  hi ToolbarButton guifg=#fbf1c7 guibg=#665c54 gui=bold cterm=bold
  hi ToolbarLine guifg=NONE guibg=#665c54 gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#665c54 gui=NONE cterm=NONE
  hi WildMenu guifg=#83a598 guibg=#504945 gui=bold cterm=bold
  hi Conceal guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi DiffAdd guifg=#b8bb26 guibg=#282828 gui=reverse cterm=reverse
  hi DiffChange guifg=#8ec07c guibg=#282828 gui=reverse cterm=reverse
  hi DiffDelete guifg=#fb4934 guibg=#282828 gui=reverse cterm=reverse
  hi DiffText guifg=#fabd2f guibg=#282828 gui=reverse cterm=reverse
  hi Directory guifg=#b8bb26 guibg=NONE gui=bold cterm=bold
  hi EndOfBuffer guifg=#282828 guibg=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=#665c54 guibg=#ebdbb2 gui=reverse cterm=reverse
  hi ModeMsg guifg=#fabd2f guibg=NONE gui=bold cterm=bold
  hi MoreMsg guifg=#fabd2f guibg=NONE gui=bold cterm=bold
  hi Question guifg=#fe8019 guibg=NONE gui=bold cterm=bold
  hi Search guifg=#ebdbb2 guibg=#282828 gui=reverse cterm=reverse
  hi SpellBad guifg=#fb4934 guibg=NONE guisp=#fb4934 gui=italic,undercurl cterm=italic,underline
  hi SpellCap guifg=#83a598 guibg=NONE guisp=#83a598 gui=italic,undercurl cterm=italic,underline
  hi SpellLocal guifg=#8ec07c guibg=NONE guisp=#8ec07c gui=italic,undercurl cterm=italic,underline
  hi SpellRare guifg=#d3869b guibg=NONE guisp=#d3869b gui=italic,undercurl cterm=italic,underline
  hi Title guifg=#b8bb26 guibg=NONE gui=bold cterm=bold
  hi WarningMsg guifg=#fb4934 guibg=NONE gui=bold cterm=bold
  hi Boolean guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
  hi Character guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
  hi Conditional guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
  hi Constant guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
  hi Define guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
  hi Debug guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#fb4934 guibg=#282828 gui=bold,reverse cterm=bold,reverse
  hi Exception guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
  hi Float guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
  hi Function guifg=#b8bb26 guibg=NONE gui=bold cterm=bold
  hi Identifier guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
  hi Ignore guifg=fg guibg=NONE gui=NONE cterm=NONE
  hi Include guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
  hi Label guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
  hi Macro guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
  hi Number guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
  hi Operator guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
  hi PreCondit guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
  hi Repeat guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
  hi SpecialChar guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
  hi SpecialComment guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#fe8019 guibg=NONE gui=italic cterm=italic
  hi String guifg=#b8bb26 guibg=NONE gui=italic cterm=italic
  hi Structure guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=fg guibg=#282828 gui=bold,italic cterm=bold,italic
  hi Type guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
  hi Typedef guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#83a598 guibg=NONE guisp=#83a598 gui=underline cterm=underline
  hi CursorIM guifg=NONE guibg=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  if !s:italics
    hi Comment gui=NONE cterm=NONE
    hi Folded gui=NONE cterm=NONE
    hi SpellBad gui=undercurl cterm=underline
    hi SpellCap gui=undercurl cterm=underline
    hi SpellLocal gui=undercurl cterm=underline
    hi SpellRare gui=undercurl cterm=underline
    hi Special gui=NONE cterm=NONE
    hi String gui=NONE cterm=NONE
    hi Todo gui=bold cterm=bold
  endif
  if !get(g:, 'gruvbox_italicize_strings', 1)
    hi Special gui=NONE cterm=NONE
    hi String gui=NONE cterm=NONE
  endif
  if !get(g:, 'gruvbox_bold', 1)
    hi Directory gui=NONE cterm=NONE
    hi Error gui=reverse cterm=reverse
    hi ErrorMsg gui=NONE cterm=NONE
    hi Function gui=NONE cterm=NONE
    hi MatchParen gui=underline cterm=underline
    hi ModeMsg gui=NONE cterm=NONE
    hi MoreMsg gui=NONE cterm=NONE
    hi PmenuSel gui=NONE cterm=NONE
    hi Question gui=NONE cterm=NONE
    hi Title gui=NONE cterm=NONE
    hi Todo gui=italic cterm=italic
    hi ToolbarButton gui=NONE cterm=NONE
    hi WarningMsg gui=NONE cterm=NONE
    hi WildMenu gui=NONE cterm=NONE
  endif
  hi NormalMode guifg=#a89984 guibg=#282828 gui=reverse cterm=reverse
  hi InsertMode guifg=#83a598 guibg=#282828 gui=reverse cterm=reverse
  hi ReplaceMode guifg=#8ec07c guibg=#282828 gui=reverse cterm=reverse
  hi VisualMode guifg=#fe8019 guibg=#282828 gui=reverse cterm=reverse
  hi CommandMode guifg=#d3869b guibg=#282828 gui=reverse cterm=reverse
  hi Warnings guifg=#fe8019 guibg=#282828 gui=reverse cterm=reverse
  if has('nvim')
    hi! link TermCursor Cursor
    hi TermCursorNC guifg=#3c3836 guibg=#ebdbb2 gui=NONE cterm=NONE
  endif
endif
