# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = '''$directory$git_branch$rust(yellow)$package
[➜ ](fg:#d65d0e)
'''

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](fg:#d65d0e)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

[directory]
style = "fg:#458588"
#format = "'[$path]($style)[$read_only]($read_only_style) '"

[rust]
style = "fg:#d65d0e"

# Disable the package module, hiding it from the prompt completely
[package]
style = "yellow"
# disabled = true
